name: verycall
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: remoch/hedera
    build_command: npm install
    run_command: node src/index.js
    envs:
      - key: TWILIO_ACCOUNT_SID
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_AUTH_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: HEDERA_ACCOUNT_ID
        scope: RUN_TIME
        type: SECRET
      - key: HEDERA_PRIVATE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: HEDERA_TOPIC_ID
        scope: RUN_TIME
        type: SECRET
      - key: BASE_URL
        scope: RUN_TIME
        value: ${APP_URL}
